name: example
description: A example of pedantic_mono.
version: 1.0.0
publish_to: none
environment:
  sdk: '>=2.2.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  meta: any
  pedantic: any
  pedantic_mono:
    path: ..
