name: pedantic_mono
description: '[mono edition] How to get the most value from Dart static analysis.'
version: 1.13.0
homepage: https://github.com/mono0926/pedantic_mono

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter_lints: ^1.0.3

dev_dependencies:
  grinder:
  http:
  yaml: