name: pedantic_mono
description: '[mono edition] How to get the most value from Dart static analysis.'
version: 1.12.1-dev
homepage: https://github.com/mono0926/pedantic_mono

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dev_dependencies:
  pedantic: '>=1.11.0 <2.0.0'
